global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Linq.Enumerators;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Threading;
global using Puzzles.Matching.Analytics;
global using Puzzles.Matching.Concepts;
global using Puzzles.Meta.DataStructures;
global using ItemIndex = byte;
