global using System;
global using System.Buffers;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Linq.Enumerators;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using Puzzles.Concepts;
global using Puzzles.Flow.Analytics;
global using Puzzles.Flow.Buffers;
global using Puzzles.Flow.Concepts;
global using Puzzles.Meta;
global using static System.Math;
global using Cell = byte;
global using Color = byte;
global using ColorMask = short;
global using Path = Puzzles.Flow.Concepts.Path;
global using Position = byte;
