global using System;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using Puzzles.Flow.Concepts;
global using Puzzles.Flow.Concepts.Primitives;
global using Puzzles.Flow.Drawing;
global using static Puzzles.Flow.ProjectWideConstants;
