global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Linq.Enumerators;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Text;
global using Puzzles.Concepts;
global using Puzzles.Flow.Concepts.Formatting;
global using Puzzles.Meta;
global using Puzzles.Meta.DataStructures;
global using Color = byte;
